name: Unit Tests & Coverage

on: [push]

jobs:
  Code-Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          tools: composer:v2
          php-version: ${{ matrix.php-version }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction

      - name: Execute unit tests with code coverage
        run: vendor/bin/phpunit --coverage-clover public/coverage/clover.xml

      - if: github.event_name == 'push' && ! contains(github.event.push.user.login, 'dependabot[bot]')
        name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: public/coverage/clover.xml
          threshold_alert: 80
          threshold_warning: 95

      - name: Generate coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          report: public/coverage/clover.xml

      - name: Retrieve the logs
        if: ${{ failure() }}
        run: cat storage/logs/*
